import type { Metadata } from "next";
import { SiteHeader } from "@/components/layout/site-header";
import { SiteFooter } from "@/components/layout/site-footer";
import { Reveal } from "@/components/motion/reveal";

export const metadata: Metadata = {
  title: "Terms of Service",
  description:
    "PageGoblin terms of service covering acceptable use, roast report content, privacy, limitations, and contact information.",
  alternates: { canonical: "/terms" },
  openGraph: {
    title: "PageGoblin Terms of Service",
    description: "Terms for using PageGoblin website roasts, reports, and the Chrome extension.",
    url: "/terms",
  },
};


const sections = [
  {
    title: "Acceptance",
    content:
      "By using PageGoblin, you agree to these terms. If you don't agree, the goblin understands — but it can't roast for free without some ground rules.",
  },
  {
    title: "Service description",
    content:
      "PageGoblin is a website analysis tool that provides humorous but practical feedback on web pages. It evaluates trust signals, CTA clarity, copy quality, and conversion friction. Roasts are opinions generated by deterministic analysis — not professional consulting advice.",
  },
  {
    title: "Acceptable use",
    content:
      "Only roast pages you own or have permission to analyze. Don't use PageGoblin to harass, bully, or target individuals. Don't abuse the API with excessive automated requests. The goblin has standards.",
  },
  {
    title: "Roast content",
    content:
      "Roasts are generated by deterministic analysis. They are opinions, not professional advice. The goblin's humor is not personal — it roasts pages, not people. Take the feedback, fix your site, and move on.",
  },
  {
    title: "Limitation of liability",
    content:
      'PageGoblin is provided "as is" without warranties of any kind. We are not liable for any damages arising from use of the service, including but not limited to hurt feelings from particularly savage roasts.',
  },
  {
    title: "Privacy",
    content:
      "Your use of PageGoblin is also governed by our Privacy Policy. Please review it to understand how we handle your data.",
  },
  {
    title: "Changes to terms",
    content:
      "We may update these terms from time to time. When we do, we'll update the date at the top of this page. Continued use of PageGoblin after changes constitutes acceptance of the new terms.",
  },
  {
    title: "Contact",
    content:
      "Questions about these terms? Reach out at info@codezela.com.",
  },
];

export default function TermsPage() {
  return (
    <>
      <SiteHeader />
      <main className="flex flex-1 flex-col items-center bg-grain">
        <section className="w-full px-6 pt-24 pb-16 text-center">
          <div className="mx-auto max-w-3xl">
            <Reveal>
              <h1 className="font-display text-4xl font-bold tracking-tight text-ink sm:text-5xl">
                Terms of Service
              </h1>
            </Reveal>
            <Reveal delay={0.1}>
              <p className="mt-4 text-sm text-muted">
                Last updated: June 2026
              </p>
            </Reveal>
            <Reveal delay={0.15}>
              <p className="mx-auto mt-6 max-w-xl text-lg leading-relaxed text-muted">
                The fine print. Not as fun as roasts, but just as important.
              </p>
            </Reveal>
          </div>
        </section>

        <section className="w-full border-t border-border bg-bone/40 px-6 py-24">
          <div className="mx-auto max-w-3xl">
            <div className="space-y-12">
              {sections.map((section, i) => (
                <Reveal key={section.title} delay={i * 0.05}>
                  <div>
                    <h2 className="font-display text-xl font-bold tracking-tight text-ink">
                      {section.title}
                    </h2>
                    <p className="mt-3 leading-relaxed text-muted">
                      {section.content}
                    </p>
                  </div>
                </Reveal>
              ))}
            </div>
          </div>
        </section>
      </main>
      <SiteFooter />
    </>
  );
}
